### ISSUE TITLE
自增加的问题

### ISSUE THREAD

**Issue by PowerAngelXD** [XtherDevTeam/Xscript#1]
目前Xscript的自增加的语法很奇怪：
(i)++或++(i)

**Comment by leadsoft-ware** [comment]
Thanks for your issue.
Here is my reply:
It's not bug, it's feature XD

I **won't** change it if it works fine.
If the program works, then don't try to change it. You don't know when it will show "SIGSEGV" like checks/debug.xs0

And here is an important feature too:

If we used syntax like `i++`, then it can't do some works like `(i, j)++` ( ` (i, j) ++ ` equals `i++; j++` ) 
It's really coooooooooooooooooooool!

**Comment by PowerAngelXD** [comment]
cool
